# If not running interactively, don't do anything
[[ $- != *i* ]] && return
source ~/.config/bash/bash_aliases
source ~/.config/bash/bash_exports
source /usr/share/doc/find-the-command/ftc.bash
source ~/.config/bash/prompt
chainos-pfetch
source ~/.config/bash/historyrc
